import { withOrgContext, type DbTransaction } from "@db/index";
import {
  ChatMessage,
  ChatMessageRole,
  ChatSession,
  chatMessages,
  chatSessions,
} from "@db/schema";
import { and, asc, desc, eq, inArray, isNull } from "drizzle-orm";
import {
  deriveSessionTitle,
  isAutoGeneratedTitle,
  isLegacyQuestionTitle,
  sanitizeBrainTitle,
} from "@/lib/chat";
import { decodeAssistantContent } from "@/lib/chat-trace";
import { runWorkflowSync } from "@/server/brain/client";

const TITLE_WORKFLOW_CODE = "WF-CHAT-TITLE";

const HISTORY_MESSAGE_LIMIT = 40;

export { deriveSessionTitle };

function ownedSessionClause(
  organisationId: string,
  sessionId: string,
  createdByUserId: string
) {
  return and(
    eq(chatSessions.id, sessionId),
    eq(chatSessions.organisationId, organisationId),
    eq(chatSessions.createdByUserId, createdByUserId)
  );
}

async function getOwnedSession(
  tx: DbTransaction,
  organisationId: string,
  sessionId: string,
  createdByUserId: string
): Promise<ChatSession | null> {
  const [session] = await tx
    .select()
    .from(chatSessions)
    .where(ownedSessionClause(organisationId, sessionId, createdByUserId))
    .limit(1);

  return session ?? null;
}

export async function listSessions(
  organisationId: string,
  createdByUserId?: string
): Promise<ChatSession[]> {
  return withOrgContext(organisationId, async tx => {
    const conditions = [
      eq(chatSessions.organisationId, organisationId),
      isNull(chatSessions.archivedAt),
    ];

    if (createdByUserId) {
      conditions.push(eq(chatSessions.createdByUserId, createdByUserId));
    }

    const sessions = await tx
      .select()
      .from(chatSessions)
      .where(and(...conditions))
      .orderBy(desc(chatSessions.lastMessageAt));

    return refreshLegacySessionTitles(tx, sessions);
  });
}

async function refreshLegacySessionTitles(
  tx: DbTransaction,
  sessions: ChatSession[]
): Promise<ChatSession[]> {
  if (sessions.length === 0) return sessions;

  const firstMessages = await tx
    .select({
      sessionId: chatMessages.sessionId,
      content: chatMessages.content,
    })
    .from(chatMessages)
    .where(
      and(
        inArray(
          chatMessages.sessionId,
          sessions.map(session => session.id)
        ),
        eq(chatMessages.role, "user")
      )
    )
    .orderBy(asc(chatMessages.createdAt));

  const firstBySession = new Map<string, string>();
  for (const row of firstMessages) {
    if (!firstBySession.has(row.sessionId)) {
      firstBySession.set(row.sessionId, row.content);
    }
  }

  const next = sessions.map(session => ({ ...session }));
  await Promise.all(
    next.map(async session => {
      const first = firstBySession.get(session.id);
      if (!first || !isLegacyQuestionTitle(session.title, first)) {
        return;
      }
      const title = deriveSessionTitle(first);
      if (title === session.title) return;
      await tx
        .update(chatSessions)
        .set({ title, updatedAt: new Date() })
        .where(eq(chatSessions.id, session.id));
      session.title = title;
    })
  );

  return next;
}

export async function createSession(
  organisationId: string,
  createdByUserId: string,
  title = "New chat"
): Promise<ChatSession> {
  return withOrgContext(organisationId, async tx => {
    const [session] = await tx
      .insert(chatSessions)
      .values({
        organisationId,
        createdByUserId,
        title,
      })
      .returning();

    return session;
  });
}

export async function getSession(
  organisationId: string,
  sessionId: string,
  createdByUserId: string
): Promise<ChatSession | null> {
  return withOrgContext(organisationId, tx =>
    getOwnedSession(tx, organisationId, sessionId, createdByUserId)
  );
}

export async function getSessionMessages(
  organisationId: string,
  sessionId: string,
  createdByUserId: string
): Promise<ChatMessage[]> {
  return withOrgContext(organisationId, async tx => {
    const session = await getOwnedSession(
      tx,
      organisationId,
      sessionId,
      createdByUserId
    );
    if (!session) {
      return [];
    }

    return tx
      .select()
      .from(chatMessages)
      .where(eq(chatMessages.sessionId, sessionId))
      .orderBy(chatMessages.createdAt);
  });
}

export async function getRecentSessionHistory(
  organisationId: string,
  sessionId: string,
  createdByUserId: string
): Promise<Array<{ role: ChatMessageRole; content: string }>> {
  const messages = await getSessionMessages(
    organisationId,
    sessionId,
    createdByUserId
  );
  return messages.slice(-HISTORY_MESSAGE_LIMIT).map(message => ({
    role: message.role,
    content:
      message.role === "assistant"
        ? decodeAssistantContent(message.content).text
        : message.content,
  }));
}

export async function appendMessage(
  organisationId: string,
  sessionId: string,
  role: ChatMessageRole,
  content: string,
  createdByUserId: string
): Promise<ChatMessage> {
  return withOrgContext(organisationId, async tx => {
    const session = await getOwnedSession(
      tx,
      organisationId,
      sessionId,
      createdByUserId
    );
    if (!session) {
      throw new Error("Chat session not found.");
    }

    const [message] = await tx
      .insert(chatMessages)
      .values({
        sessionId,
        role,
        content,
      })
      .returning();

    const shouldSetTitle =
      role === "user" && (session.title === "New chat" || !session.title);

    await tx
      .update(chatSessions)
      .set({
        lastMessageAt: new Date(),
        updatedAt: new Date(),
        ...(shouldSetTitle ? { title: deriveSessionTitle(content) } : {}),
      })
      .where(ownedSessionClause(organisationId, sessionId, createdByUserId));

    return message;
  });
}

/**
 * After the first assistant reply, ask Brain for a short title and write it
 * when the current title is still auto-generated (not a manual rename).
 */
export async function applyBrainSessionTitle(
  organisationId: string,
  sessionId: string,
  firstMessage: string,
  createdByUserId: string,
  rawTitle?: string | null
): Promise<string | null> {
  const session = await getSession(organisationId, sessionId, createdByUserId);
  if (!session || !isAutoGeneratedTitle(session.title, firstMessage)) {
    return session?.title ?? null;
  }

  if (rawTitle === null) {
    return session.title;
  }

  let raw = rawTitle;
  if (raw === undefined) {
    try {
      raw = await runWorkflowSync(TITLE_WORKFLOW_CODE, {
        inputMessage: firstMessage,
      });
    } catch (error) {
      console.error("Failed to summarise chat title:", error);
      return session.title;
    }
  }

  const title = sanitizeBrainTitle(raw);
  if (!title) return session.title;

  const latest = await getSession(organisationId, sessionId, createdByUserId);
  if (!latest || !isAutoGeneratedTitle(latest.title, firstMessage)) {
    return latest?.title ?? session.title;
  }

  const updated = await renameSession(
    organisationId,
    sessionId,
    title,
    createdByUserId
  );
  return updated?.title ?? title;
}

export async function renameSession(
  organisationId: string,
  sessionId: string,
  title: string,
  createdByUserId: string
): Promise<ChatSession | null> {
  const trimmed = title.trim();
  if (!trimmed) {
    throw new Error("title is required.");
  }

  return withOrgContext(organisationId, async tx => {
    const [updated] = await tx
      .update(chatSessions)
      .set({
        title: trimmed.slice(0, 80),
        updatedAt: new Date(),
      })
      .where(ownedSessionClause(organisationId, sessionId, createdByUserId))
      .returning();

    return updated ?? null;
  });
}

export async function deleteSession(
  organisationId: string,
  sessionId: string,
  createdByUserId: string
): Promise<boolean> {
  return withOrgContext(organisationId, async tx => {
    const deleted = await tx
      .delete(chatSessions)
      .where(ownedSessionClause(organisationId, sessionId, createdByUserId))
      .returning({ id: chatSessions.id });

    return deleted.length > 0;
  });
}
